### ISSUE TITLE
Count with positive and negative weight

### ISSUE THREAD

**Issue by bortigno** [heppynmore/heppynmore#4]
Update the code to use the positive and negative weights to reweigh the monte carlo samples. look into treeCache get_scale.

**Comment by benjaminkreis** [comment]
It looks to me like this is already handled inside HEPPY:

https://github.com/vhbb/cmssw/blob/vhbbHeppy74X/VHbbAnalysis/Heppy/python/VHbbAnalyzer.py#L422

Meaning, we make no changes.  Do you agree?

**Comment by bortigno** [comment]
oh good, thanks for checking. I see also the puWeight are included in it. ok let's close it and leave h&m as it is
